 #ifndef __USER_MAIN_H
    #define __USER_MAIN_H

#define SETUPWIFI "MGS+SETUPWIFI "
#define CHECKSTATUS_WIFI "MGS+CHECKSTATUS"
#define CONNECT_TO_SERVER1_BY_CLIENT1 "MGS+CONNECTCLIENT1 "
#define CONNECT_TO_SERVER2_BY_CLIENT2 "MGS+CONNECTCLIENT2 "
#define DISCONNECT_FROM_SERVER1 "MGS+DISCONN1"
#define DISCONNECT_FROM_SERVER2 "MGS+DISCONN2"
#define CHECKSTATUS_CLIENT1 "MGS+CONNSTAT1"
#define CHECKSTATUS_CLIENT2 "MGS+CONNSTAT2"
#define PRINT_TO_SERVER1 "MGS+PRINT1 "
#define PRINT_TO_SERVER2 "MGS+PRINT2 "
#define READ_DATA_FROM_CLIENT1_BUFFER "MGS+READ1 "
#define READ_DATA_FROM_CLIENT2_BUFFER "MGS+READ2 "
#define CONNECT_TO_NETPIE "MGS+NPCONNECT"
#define DISCONNECT_FROM_NETPIE "MGS+NPDISCONNECT"  
#define SETUP_TOKEN "MGS+TOKENSETUP "	//MGS+TOKENSETUP RKJy30tYkUKoXa7G,oWfxRNqRaXdwffVdFvuU27qJqr1KNpIy
#define INIT_MICROGEAR "MGS+INIT "		//MGS+INIT HelloNetpie1,YhtHPvlmMxL5yJB,YphWgyUI31q8sEMu6qtNrIPn1,Light_control
#define SET_ALIAS_NAME "MGS+SETALIAS "
#define PUBLISH "MGS+PUBLISH "
#define SUBSCRIBE "MGS+SUBSCRIBE "
#define UNSUBSCRIBE "MGS+UNSUBSCRIBE "
#define CHAT "MGS+CHAT "

#define MAX_SIZE_TCP_PRINT 500
#define MAX_SIZE_TCP_RECEV 500
#define MAX_SIZE_PUBLISH 50
#define MAX_SIZE_TOPIC 50






#endif
